version: "3.4"

services:
  # BUILD APPLICATION
  build:
    container_name: ${BUILD_CONTAINER_NAME}
    image: maven:3.8.6-openjdk-18
    env_file: [ .env ]
    profiles: [ build ]
    volumes:
      - ../../:/usr/src/mymaven
    working_dir: /usr/src/mymaven/gemp-lotr
    command: mvn clean verify

  # RUN DATABASE
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mariadb:10.8.3
    env_file: [ .env ]
    profiles: [ run ]
    # No need to expose the port unless needed for development/debugging
    # ports:
    #   - ${DB_PORT}:3306
    volumes:
      - ../../database/mysql:/var/lib/mysql # Folder containing the database
      - ../gemp-lotr-async/target/config/:/docker-entrypoint-initdb.d # Folder containing the scripts to run when the DB is initialized (in alphabetical order)
    restart: always

  # RUN APPLICATION
  app:
    container_name: ${APP_CONTAINER_NAME}
    image: bellsoft/liberica-openjdk-alpine:18.0.1.1-2
# TODO: Wait for SB to startup fully
    depends_on: [ db ]
    profiles: [ run ]
    env_file: [ .env ]
    ports:
      - ${APP_PORT}:80
    volumes:
      - ../gemp-lotr-async/target:/data
      - ./gemp-lotr-override.properties:/data/config/gemp-lotr-override.properties
    command: java -jar -Dgemp-lotr.override=/gemp-lotr-override.properties /data/app.jar
    restart: always
