-- COLLECTION
CREATE TABLE PUBLIC.COLLECTION (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	PLAYER_ID INT NOT NULL,
	COLLECTION BINARY VARYING(1048576) NOT NULL,
	"TYPE" CHARACTER VARYING(45) NOT NULL
);
CREATE INDEX PLAYER_COLLECTION ON PUBLIC.COLLECTION(PLAYER_ID, "TYPE");

-- DECK
CREATE TABLE PUBLIC.DECK (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	PLAYER_ID INT NOT NULL,
	NAME CHARACTER VARYING(45) NOT NULL DEFAULT 'Default',
	"TYPE" CHARACTER VARYING(45) NOT NULL DEFAULT 'Default',
	CONTENTS CHARACTER VARYING(65535) NOT NULL
);
CREATE UNIQUE INDEX PLAYER_DECK ON PUBLIC.DECK(PLAYER_ID, NAME);
CREATE INDEX PLAYER_ID ON PUBLIC.DECK(PLAYER_ID);

-- GAME_HISTORY
CREATE TABLE PUBLIC.GAME_HISTORY (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	WINNER CHARACTER VARYING(45) NOT NULL,
	LOSER CHARACTER VARYING(45) NOT NULL,
	WIN_REASON CHARACTER VARYING(255) NOT NULL,
	LOSE_REASON CHARACTER VARYING(255) NOT NULL,
	WIN_RECORDING_ID CHARACTER VARYING(45) NOT NULL,
	LOSE_RECORDING_ID CHARACTER VARYING(45) NOT NULL,
	START_DATE NUMERIC(20,0) NOT NULL,
	END_DATE NUMERIC(20,0) NOT NULL,
	FORMAT_NAME CHARACTER VARYING(45) NOT NULL,
	WINNER_DECK_NAME CHARACTER VARYING(255) NOT NULL,
	LOSER_DECK_NAME CHARACTER VARYING(255) NOT NULL,
	TOURNAMENT CHARACTER VARYING(255) NOT NULL
);
CREATE INDEX END_DATE ON PUBLIC.GAME_HISTORY(END_DATE);
CREATE INDEX INDEX3 ON PUBLIC.GAME_HISTORY(WINNER);
CREATE INDEX INDEX4 ON PUBLIC.GAME_HISTORY(LOSER);

-- IGNORES
CREATE TABLE PUBLIC.IGNORES (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	PLAYERNAME CHARACTER VARYING(10) NOT NULL,
	IGNOREDNAME CHARACTER VARYING(10) NOT NULL
);
CREATE INDEX PLAYER_IGNORES ON PUBLIC.IGNORES(PLAYERNAME);

-- IP_BAN
CREATE TABLE PUBLIC.IP_BAN (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	IP CHARACTER VARYING(255) NOT NULL,
	PREFIX INT NOT NULL
);

-- LEAGUE
CREATE TABLE PUBLIC.LEAGUE (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NAME CHARACTER VARYING(45) NOT NULL,
	"TYPE" CHARACTER VARYING(45) NOT NULL,
	CLASS CHARACTER VARYING(255) NOT NULL,
	PARAMETERS CHARACTER VARYING(255) NOT NULL,
	"START" INT NOT NULL,
	"END" INT NOT NULL,
	STATUS INT NOT NULL,
	COST INT NOT NULL DEFAULT 0
);

-- LEAGUE_MATCH
CREATE TABLE PUBLIC.LEAGUE_MATCH (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	LEAGUE_TYPE CHARACTER VARYING(45) NOT NULL,
	SEASON_TYPE CHARACTER VARYING(45) NOT NULL,
	WINNER CHARACTER VARYING(45) NOT NULL,
	LOSER CHARACTER VARYING(45) NOT NULL
);

-- LEAGUE_PARTICIPATION
CREATE TABLE PUBLIC.LEAGUE_PARTICIPATION (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	LEAGUE_TYPE CHARACTER VARYING(45) NOT NULL,
	PLAYER_NAME CHARACTER VARYING(45) NOT NULL,
	JOIN_IP CHARACTER VARYING(45) DEFAULT NULL
);

-- PLAYER
CREATE TABLE PUBLIC.PLAYER (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NAME CHARACTER VARYING(10) NOT NULL,
	PASSWORD CHARACTER VARYING(64) NOT NULL,
	"TYPE" CHARACTER VARYING(5) NOT NULL DEFAULT 'u',
	LAST_LOGIN_REWARD INT DEFAULT NULL,
	LAST_IP CHARACTER VARYING(45) DEFAULT NULL,
	CREATE_IP CHARACTER VARYING(45) DEFAULT NULL,
	BANNED_UNTIL NUMERIC(20,0) DEFAULT NULL
);
CREATE UNIQUE INDEX name_UNIQUE ON PUBLIC.PLAYER(NAME);

-- SCHEDULED_TOURNAMENT
CREATE TABLE PUBLIC.SCHEDULED_TOURNAMENT (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TOURNAMENT_ID CHARACTER VARYING(45) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	FORMAT CHARACTER VARYING(45) NOT NULL,
	"START" NUMERIC(20,0) NOT NULL,
	COST NUMERIC(10,0) NOT NULL,
	PLAYOFF CHARACTER VARYING(45) NOT NULL,
	PRIZES CHARACTER VARYING(45) NOT NULL,
	MINIMUM_PLAYERS NUMERIC(3,0) NOT NULL,
	STARTED NUMERIC(1,0) NOT NULL DEFAULT 0
);
CREATE INDEX STARTED ON PUBLIC.SCHEDULED_TOURNAMENT(STARTED);

-- TOURNAMENT
CREATE TABLE PUBLIC.TOURNAMENT (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TOURNAMENT_ID CHARACTER VARYING(255) NOT NULL,
	"START" NUMERIC(20,0) NOT NULL,
	DRAFT_TYPE CHARACTER VARYING(45) DEFAULT NULL,
	NAME CHARACTER VARYING(255) DEFAULT NULL,
	FORMAT CHARACTER VARYING(255) DEFAULT NULL,
	COLLECTION CHARACTER VARYING(255) DEFAULT NULL,
	STAGE CHARACTER VARYING(45) DEFAULT NULL,
	PAIRING CHARACTER VARYING(45) DEFAULT NULL,
	ROUND INT DEFAULT NULL,
	PRIZES CHARACTER VARYING(45) DEFAULT NULL
);

-- TOURNAMENT_MATCH
CREATE TABLE PUBLIC.TOURNAMENT_MATCH (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TOURNAMENT_ID CHARACTER VARYING(255) NOT NULL,
	ROUND NUMERIC(2,0) NOT NULL,
	PLAYER_ONE CHARACTER VARYING(45) NOT NULL,
	PLAYER_TWO CHARACTER VARYING(45) NOT NULL,
	WINNER CHARACTER VARYING(45) DEFAULT NULL
);

-- TOURNAMENT_PLAYER
CREATE TABLE PUBLIC.TOURNAMENT_PLAYER (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TOURNAMENT_ID CHARACTER VARYING(255) NOT NULL,
	PLAYER CHARACTER VARYING(10) NOT NULL,
	DECK_NAME CHARACTER VARYING(45) NOT NULL,
	DECK CHARACTER VARYING(65535) NOT NULL,
	DROPPED BINARY(1) NOT NULL DEFAULT 0
);


-- TRANSFER definition
CREATE TABLE PUBLIC.TRANSFER (
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NOTIFY INT NOT NULL,
	PLAYER CHARACTER VARYING(45) NOT NULL,
	REASON CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	CURRENCY INT NOT NULL,
	COLLECTION CHARACTER VARYING(65535) NOT NULL,
	TRANSFER_DATE NUMERIC(20,0) NOT NULL,
	DIRECTION CHARACTER VARYING(45) NOT NULL
);
CREATE INDEX PLAYER ON PUBLIC.TRANSFER(PLAYER, NOTIFY);
