

-- TODO: Still need to add the Primary Keys, Indexes, etc.




-- PUBLIC.COLLECTION definition

-- Drop table

-- DROP TABLE PUBLIC.COLLECTION;

CREATE TABLE PUBLIC.COLLECTION (
	ID TINYINT NOT NULL,
	PLAYER_ID TINYINT NOT NULL,
	COLLECTION BINARY VARYING(16777215),
	"TYPE" CHARACTER(45)
);


-- PUBLIC.DECK definition

-- Drop table

-- DROP TABLE PUBLIC.DECK;

CREATE TABLE PUBLIC.DECK (
	ID TINYINT NOT NULL,
	PLAYER_ID TINYINT NOT NULL,
	NAME CHARACTER(45),
	"TYPE" CHARACTER(45),
	CONTENTS CHARACTER(65535)
);


-- PUBLIC.GAME_HISTORY definition

-- Drop table

-- DROP TABLE PUBLIC.GAME_HISTORY;

CREATE TABLE PUBLIC.GAME_HISTORY (
	ID TINYINT NOT NULL,
	WINNER CHARACTER(45),
	LOSER CHARACTER(45),
	WIN_REASON CHARACTER(255),
	LOSE_REASON CHARACTER(255),
	WIN_RECORDING_ID CHARACTER(45),
	LOSE_RECORDING_ID CHARACTER(45),
	START_DATE NUMERIC(20,0),
	END_DATE NUMERIC(20,0),
	FORMAT_NAME CHARACTER(45),
	WINNER_DECK_NAME CHARACTER(255),
	LOSER_DECK_NAME CHARACTER(255),
	TOURNAMENT CHARACTER(255)
);


-- PUBLIC.IGNORES definition

-- Drop table

-- DROP TABLE PUBLIC.IGNORES;

CREATE TABLE PUBLIC.IGNORES (
	ID TINYINT NOT NULL,
	PLAYERNAME CHARACTER(10),
	IGNOREDNAME CHARACTER(10)
);


-- PUBLIC.IP_BAN definition

-- Drop table

-- DROP TABLE PUBLIC.IP_BAN;

CREATE TABLE PUBLIC.IP_BAN (
	ID TINYINT NOT NULL,
	IP CHARACTER(255),
	PREFIX TINYINT NOT NULL
);


-- PUBLIC.LEAGUE definition

-- Drop table

-- DROP TABLE PUBLIC.LEAGUE;

CREATE TABLE PUBLIC.LEAGUE (
	ID TINYINT NOT NULL,
	NAME CHARACTER(45),
	"TYPE" CHARACTER(45),
	CLASS CHARACTER(255),
	PARAMETERS CHARACTER(255),
	"START" TINYINT NOT NULL,
	"END" TINYINT NOT NULL,
	STATUS TINYINT NOT NULL,
	COST TINYINT NOT NULL
);


-- PUBLIC.LEAGUE_MATCH definition

-- Drop table

-- DROP TABLE PUBLIC.LEAGUE_MATCH;

CREATE TABLE PUBLIC.LEAGUE_MATCH (
	ID TINYINT NOT NULL,
	LEAGUE_TYPE CHARACTER(45),
	SEASON_TYPE CHARACTER(45),
	WINNER CHARACTER(45),
	LOSER CHARACTER(45)
);


-- PUBLIC.LEAGUE_PARTICIPATION definition

-- Drop table

-- DROP TABLE PUBLIC.LEAGUE_PARTICIPATION;

CREATE TABLE PUBLIC.LEAGUE_PARTICIPATION (
	ID TINYINT NOT NULL,
	LEAGUE_TYPE CHARACTER(45),
	PLAYER_NAME CHARACTER(45),
	JOIN_IP CHARACTER(45)
);


-- PUBLIC.PLAYER definition

-- Drop table

-- DROP TABLE PUBLIC.PLAYER;

CREATE TABLE PUBLIC.PLAYER (
	ID TINYINT NOT NULL,
	NAME CHARACTER(10),
	PASSWORD CHARACTER(64),
	"TYPE" CHARACTER(5),
	LAST_LOGIN_REWARD TINYINT,
	LAST_IP CHARACTER(45),
	CREATE_IP CHARACTER(45),
	BANNED_UNTIL NUMERIC(20,0)
);


-- PUBLIC.SCHEDULED_TOURNAMENT definition

-- Drop table

-- DROP TABLE PUBLIC.SCHEDULED_TOURNAMENT;

CREATE TABLE PUBLIC.SCHEDULED_TOURNAMENT (
	ID TINYINT NOT NULL,
	TOURNAMENT_ID CHARACTER(45),
	NAME CHARACTER(255),
	FORMAT CHARACTER(45),
	"START" NUMERIC(20,0),
	COST NUMERIC(10,0),
	PLAYOFF CHARACTER(45),
	PRIZES CHARACTER(45),
	MINIMUM_PLAYERS NUMERIC(3,0),
	STARTED NUMERIC(1,0)
);


-- PUBLIC.TOURNAMENT definition

-- Drop table

-- DROP TABLE PUBLIC.TOURNAMENT;

CREATE TABLE PUBLIC.TOURNAMENT (
	ID TINYINT NOT NULL,
	TOURNAMENT_ID CHARACTER(255),
	"START" NUMERIC(20,0),
	DRAFT_TYPE CHARACTER(45),
	NAME CHARACTER(255),
	FORMAT CHARACTER(255),
	COLLECTION CHARACTER(255),
	STAGE CHARACTER(45),
	PAIRING CHARACTER(45),
	ROUND TINYINT,
	PRIZES CHARACTER(45)
);


-- PUBLIC.TOURNAMENT_MATCH definition

-- Drop table

-- DROP TABLE PUBLIC.TOURNAMENT_MATCH;

CREATE TABLE PUBLIC.TOURNAMENT_MATCH (
	ID TINYINT NOT NULL,
	TOURNAMENT_ID CHARACTER(255),
	ROUND NUMERIC(2,0),
	PLAYER_ONE CHARACTER(45),
	PLAYER_TWO CHARACTER(45),
	WINNER CHARACTER(45)
);


-- PUBLIC.TOURNAMENT_PLAYER definition

-- Drop table

-- DROP TABLE PUBLIC.TOURNAMENT_PLAYER;

CREATE TABLE PUBLIC.TOURNAMENT_PLAYER (
	ID TINYINT NOT NULL,
	TOURNAMENT_ID CHARACTER(255),
	PLAYER CHARACTER(10),
	DECK_NAME CHARACTER(45),
	DECK CHARACTER(65535),
	DROPPED BINARY(1)
);


-- PUBLIC.TRANSFER definition

-- Drop table

-- DROP TABLE PUBLIC.TRANSFER;

CREATE TABLE PUBLIC.TRANSFER (
	ID TINYINT NOT NULL,
	NOTIFY TINYINT NOT NULL,
	PLAYER CHARACTER(45),
	REASON CHARACTER(255),
	NAME CHARACTER(255),
	CURRENCY TINYINT NOT NULL,
	COLLECTION CHARACTER(65535),
	TRANSFER_DATE NUMERIC(20,0),
	DIRECTION CHARACTER(45)
);