version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=gemp_R00t
      - MARIADB_DATABASE=gemp_db
      - MARIADB_USER=gempuser
      - MYSQL_PASSWORD=gemppassword
    ports:
      - 3306:3306
